project:
  type: website
  output-dir: docs

website:
  title: "Davidson DataFest"
  repo-url: https://github.com/DavidsonCollege-DataScience/datafest
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: 
    center: |
      [![](/img/davidson-wordmark-horizontal-lockup-white_sm.png){fig-alt="Davidson College" target="_blank" width=200px}](https://davidson.edu)
    right: "Made with Quarto" 
    background: "#0f1012"
    foreground: "#ffffff"
  announcement: 
    icon: info-circle
    dismissable: false
    content: "Early registration for DataFest registration is open until March 1!"
    type: info
    position: below-navbar
    
  navbar:
    search: false
    right:
      - text: About
        href: index.qmd#about
      - text: Schedule
        href: index.qmd#schedule
      - text: FAQ
        href: index.qmd#faq
      - text: Sponsors
        href: index.qmd#sponsors
      - sidebar:prevyears
    tools:
      - icon: github
        href: https://github.com/DavidsonCollege-DataScience/datafest
        target: _blank
      
  sidebar:
    - id: prevyears
      title: "Previous Events"   
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
      - text: "DataFest 2025"
        href: datafest2025.qmd

format:
  html:
    backgroundcolor: "#e6e6e6" 
    fontcolor: "black"
    linkcolor: "black"
    mainfont: "Atkinson Hyperlegible"
    fontsize: 20px
    theme: [materia, styles.scss]
    
