project:
  type: website
  output-dir: docs

website:
  title: "Davidson DataFest"
  site-url: https://davidsoncollege-datascience.github.io/datafest
  repo-url: https://github.com/DavidsonCollege-DataScience/datafest
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  favicon: img/Circle-favicon-32x32.png
  page-footer: 
    center: |
      [![](/img/davidson-wordmark-horizontal-lockup-white_sm.png){fig-alt="Davidson College" target="_blank" width="50%"}](https://davidson.edu)
    right: "Made with Quarto" 
    background: "#0f1012"
    foreground: "#ffffff"
  announcement: 
    icon: info-circle
    dismissable: false
    content: "Early registration for DataFest is open until March 1!"
    type: dark
    position: below-navbar
    
  navbar:
    search: false
    right:
      - text: "<span class='btn btn-light'>Register now!</span>"
        href: https://forms.gle/tCDkfefZRxTFJRH79
      - text: About
        href: index.qmd#about
      - text: Location
        href: index.qmd#location
      - text: Schedule
        href: index.qmd#schedule
      - text: FAQ
        href: index.qmd#faq
      - text: Sponsors
        href: index.qmd#sponsors
      - text: Blog
        href: index.qmd#blog
    # tools:
    #   - icon: github
    #     href: https://github.com/DavidsonCollege-DataScience/datafest
    #     target: _blank

format:
  html:
    backgroundcolor: "#e6e6e6" 
    fontcolor: "black"
    linkcolor: "black"
    mainfont: "Atkinson Hyperlegible"
    fontsize: 20px
    theme: [materia, styles.scss]
    
